name: "ci-cd ThreeJs project"

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm install

      - name: Build file
        run: npm run build

      # // deploy the application to netlify
      - name: Deploy production to Netlify
        # uses: South-Paw/action-netlify-deploy@v1.2.0
        # with:
        #   github-token: ${{ secrets.GITHUB_TOKEN }}
        #   netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        #   netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
        #   build-dir: "./build"
        #   comment-on-commit: true

          script:
            - echo "REACT_APP_BASE_URL=https://culturenet-apis.netlify.app/.netlify/functions/api" >> ".env"
            - npm install --legacy-peer-deps
            - npm install netlify-cli -g
            - npm run build
            # - netlify link --id af6ba939-984a-4e41-ae5f-71f43598b714
            - netlify deploy --dir "dist" --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --site ${{ secrets.NETLIFY_SITE_ID }} --prod